[theme]
base="light"
primaryColor="#163820"
backgroundColor="#F3EEE3"
secondaryBackgroundColor="#EAE2D2"
textColor="#0E2615"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
